CREATE TABLE FEATURETYPE (

   ID INTEGER NOT NULL PRIMARY KEY,
   ATTFULL NUMBER,
   ATTFULLNN NUMBER NOT NULL,
   ATTINT INTEGER,
   ATTINTNN INTEGER NOT NULL
);

CREATE TABLE FEATURETYPE_ATTSINGLE (

   FEATURETYPEID INTEGER NOT NULL,
   ATTSINGLE NUMBER NOT NULL,
   PRIMARY KEY (FEATURETYPEID, ATTSINGLE)
);

CREATE TABLE FEATURETYPE_ATTSINGLENN (

   FEATURETYPEID INTEGER NOT NULL,
   ATTSINGLENN NUMBER NOT NULL,
   PRIMARY KEY (FEATURETYPEID, ATTSINGLENN)
);


ALTER TABLE FEATURETYPE ADD CONSTRAINT FEATURETYPE_ATTFULLNN_CK CHECK (ATTFULLNN BETWEEN -5.5 AND 5.5);
ALTER TABLE FEATURETYPE ADD CONSTRAINT FEATURETYPE_ATTFULL_CK CHECK (ATTFULL IS NULL OR ATTFULL BETWEEN -5.5 AND 5.5);
ALTER TABLE FEATURETYPE ADD CONSTRAINT FEATURETYPE_ATTINTNN_CK CHECK (ATTINTNN BETWEEN -1000000000 AND 2);
ALTER TABLE FEATURETYPE ADD CONSTRAINT FEATURETYPE_ATTINT_CK CHECK (ATTINT IS NULL OR ATTINT BETWEEN -2 AND 1000000000);
ALTER TABLE FEATURETYPE_ATTSINGLE ADD CONSTRAINT FEATURETYPE_A_ATTSINGLE_CK CHECK (ATTSINGLE BETWEEN -3.3 AND 1000000000);
ALTER TABLE FEATURETYPE_ATTSINGLE ADD CONSTRAINT FK_FEATURETYPE_ATTSINGLE_FEATU FOREIGN KEY (FEATURETYPEID) REFERENCES FEATURETYPE;
ALTER TABLE FEATURETYPE_ATTSINGLENN ADD CONSTRAINT FEATURETYPE_A_ATTSINGLENN_CK CHECK (ATTSINGLENN BETWEEN -1000000000 AND 3.3);
ALTER TABLE FEATURETYPE_ATTSINGLENN ADD CONSTRAINT FK_FEATURETYPE_ATTSINGLENN_FEA FOREIGN KEY (FEATURETYPEID) REFERENCES FEATURETYPE;
