-- TOP CONTENT
-- TOP CONTENT
-- TOP CONTENT
CREATE TABLE featuretype (
   _id bigserial NOT NULL PRIMARY KEY,
   att1 character varying(1024) NOT NULL
);
-- BOTTOM CONTENT
-- BOTTOM CONTENT
-- BOTTOM CONTENT
