:doctype: book
:encoding: utf-8
:lang: en
:toc: macro
:toc-title: Table of contents
:toclevels: 5

:toc-position: left

:appendix-caption: Annex

:numbered:
:sectanchors:
:sectnumlevels: 5
:nofooter:

[[Basic_Model_Validator]]
= Basic Model Validator

(since v3.1.0)

[[Introduction]]
== Introduction

This model validator can check if the values of model element 
descriptors and tags match a given regular expression. 

IMPORTANT: Only model elements from the schemas selected 
for processing will be tested! The configuration of the actual 
transformation or target, which provides the execution context
of the validator, defines which schemas are selected for processing.
For further details, see the documentation of xref:../transformations/Common_Transformer_Functionality.adoc#Selecting_the_Schemas_to_Process[transformers] and xref:../targets/Output_Targets.adoc#Selecting_the_Schemas_to_Process[targets].

[[Configuration]]
== Configuration

The following sections specifiy the configuration options for this
model validator.

[[Class]]
=== Class

The class for this model validator implementation is
_de.interactive_instruments.shapechange.core.modelvalidation.basic.BasicModelValidator_

[[Rules]]
=== Rules

_No specific rules have been defined so far._
 
Simply configure basic content tests in the 
advanced process configuration, to define the checks 
that shall be performed for a given model.

[[Parameters]]
=== Parameters

_None at present_

[[Advanced_Process_Configuration]]
=== Advanced Process Configuration

[[Basic_Content_Tests]]
==== Basic Content Tests

The validator supports checks of descriptor and tag values for model elements, 
using regular expressions. More checks can be added in the future. To specify
the checks, the `<BasicContentTests>` element needs to be added within the 
`<advancedProcessConfigurations>` element of the validator. There is a single
child element, `<tests>`, which contains a sequence of one or more `<DescriptorContentTest>` 
elements.

A configuration example is shown <<Sample_Configuration,here>>.

[#table_descriptor_content_test_element,reftext='{table-caption} {counter:table-num}']
.DescriptorContentTest element
[cols="1,1,1,1,6a",options="header"]
|===
| Configuration Information Item | Datatype & Structure | Required / Optional | Default Value | Description
| descriptorOr TaggedValue | string | Required | _not applicable_ | Either a _descriptor-ID_, identifying one of the xref:../get started/The_element_input.adoc#table_descriptors[well-known descriptors], or a string identifying a tagged value. 

In order to identify a tagged value, add prefix "TV:" to the name of the tagged value. If a tagged value is known to contain a list of values, combined in a string using a specific separator, and these values shall be used as individual values, rather than using the whole string as value, use the prefix "TV(_separator_):," followed by the tag name. ShapeChange will then split the tagged value around matches of the given separator (which is treated as a literal).
| regex | string with regular expression (using the syntax supported by Java) | Required | _not applicable_ | If all values of the descriptor or tag match the regular expression, this filter criterium evaluates to true. If no value was found, the empty string will be assumed as value (and thus only match the regular expression if it allows an empty string).
5+| A number of attributes are used to select relevant model elements, for which the check shall be executed. They
are the same as described
xref:../transformations/Common_Transformer_Functionality.adoc#Model_element_filter_criteria[here].

|===

[[Sample_Configuration]]
== Sample Configuration

[source,xml,linenumbers]
----------
<Validator id="valPropertyTaggedValues" class="de.interactive_instruments.shapechange.core.modelvalidation.basic.BasicModelValidator" mode="enabled" validationMode="strict">
  <advancedProcessConfigurations>
    <BasicContentTests>
      <tests>
        <!-- Is the documentation of every feature type, attribute, and enum present? -->
        <DescriptorContentTest descriptorOrTaggedValue="documentation" regex="^.+$" modelElementType="Class" modelElementStereotype="(?i)featuretype"/>
        <DescriptorContentTest descriptorOrTaggedValue="documentation" regex="^.+$" modelElementType="Attribute" modelElementOwnerStereotype="(?!(?i)codelist).*"/>
        <!-- Does every property (excluding enums and codes) have tags inlineOrByReference and sequenceNumber with valid values? -->
        <DescriptorContentTest descriptorOrTaggedValue="TV:inlineOrByReference" regex="^(inline|byReference|inlineOrByReference)$" modelElementType="Property"
          modelElementOwnerStereotype="(?!(?i)(enumeration|codelist)).*"/>
        <DescriptorContentTest descriptorOrTaggedValue="TV:sequenceNumber" regex="^\d+$" modelElementType="Property" modelElementOwnerStereotype="(?!(?i)(enumeration|codelist)).*"/>
      </tests>
    </BasicContentTests>
  </advancedProcessConfigurations>
</Validator>
----------
