# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Disable actual pull requests for maven dependencies
    # open-pull-requests-limit: 0
    # Create a group of dependencies to be updated together in one pull request
    groups:
       # Specify a name for the group, which will be used in pull request titles
       # and branch names
       slf4j:
          applies-to: version-updates
          patterns:
            - "org.slf4j*"
       junit-jupiter:
          applies-to: version-updates
          patterns:
            - "org.junit.jupiter*"
       xmlunit:
          applies-to: version-updates
          patterns:
            - "org.xmlunit*"
       fasterxml-jackson:
          applies-to: version-updates
          patterns:
            - "com.fasterxml.jackson*"
       apache-poi:
          applies-to: version-updates
          patterns:
            - "org.apache.poi*"