CREATE TABLE T6_CLASS1 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   PROPBOOLEANFALSE INTEGER NOT NULL DEFAULT 0,
   PROPBOOLEANTRUE INTEGER NOT NULL DEFAULT 1,
   PROPINTEGER INTEGER NOT NULL DEFAULT 3,
   PROPNUMBER NUMBER NOT NULL DEFAULT 2.1,
   PROPSTRING CLOB NOT NULL DEFAULT 'mydefault'
);

CREATE TABLE T6_CLASS1_PROPSTRINGS (

   T6_CLASS1_ID INTEGER NOT NULL,
   PROPSTRINGS CLOB NOT NULL DEFAULT 'abc',
   PRIMARY KEY (T6_CLASS1_ID, PROPSTRINGS)
);


ALTER TABLE T6_CLASS1_PROPSTRINGS ADD CONSTRAINT FK_T6_CLASS1_PROPSTRINGS_T6_CL FOREIGN KEY (T6_CLASS1_ID) REFERENCES T6_CLASS1;
