CREATE TABLE T3_CODELIST1 (

   CODE VARCHAR2(50) NOT NULL,
   DESCRIPTION VARCHAR2(255),
   NAME VARCHAR2(255),
   ACTIVE_INDICATOR_LF CHAR(1) NULL,
   SOURCE_GCL VARCHAR(16) NULL,
   CONSTRAINT CKC_AI_T3_CODELIST1 CHECK (ACTIVE_INDICATOR_LF IS NULL OR ACTIVE_INDICATOR_LF IN ('Y', 'N')),
   CONSTRAINT PK_T3_CODELIST1 PRIMARY KEY NONCLUSTERED (CODE)
);

CREATE TABLE T3_CODELIST2 (

   CODE VARCHAR2(50) NOT NULL,
   DESCRIPTION VARCHAR2(255),
   NAME VARCHAR2(255),
   ACTIVE_INDICATOR_LF CHAR(1) NULL,
   SOURCE_GCL VARCHAR(16) NULL,
   CONSTRAINT CKC_AI_T3_CODELIST2 CHECK (ACTIVE_INDICATOR_LF IS NULL OR ACTIVE_INDICATOR_LF IN ('Y', 'N')),
   CONSTRAINT PK_T3_CODELIST2 PRIMARY KEY NONCLUSTERED (CODE)
);

CREATE TABLE T3_FEATURETYPE1 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   PROPNUMCODE VARCHAR2(50) -- DEF: propNumCode definition; DESC: propNumCode description; EX: propNumCode example 1 propNumCode example 2; LB: propNumCode legal basis; DCS: propNumCode data capture statement 1 propNumCode data capture statement 2; PC: propNumCode primary code
);

CREATE TABLE T3_FEATURETYPE1_PROPALPCODE (

   T3_FEATURETYPE1_ID INTEGER NOT NULL,
   T3_CODELIST2_ID VARCHAR2(50) NOT NULL, -- DEF: ; DESC: ; EX: ; LB: ; DCS: ; PC:
   PRIMARY KEY (T3_FEATURETYPE1_ID, T3_CODELIST2_ID)
);


ALTER TABLE T3_FEATURETYPE1 ADD CONSTRAINT FK_T3_FEATU_T3_CODEL_PROPNUMC FOREIGN KEY (PROPNUMCODE) REFERENCES T3_CODELIST1;
ALTER TABLE T3_FEATURETYPE1_PROPALPCODE ADD CONSTRAINT FK_T3_FEATU_T3_CODEL_T3_CODEL FOREIGN KEY (T3_CODELIST2_ID) REFERENCES T3_CODELIST2;
ALTER TABLE T3_FEATURETYPE1_PROPALPCODE ADD CONSTRAINT FK_T3_FEATU_T3_FEATU_T3_FEATU FOREIGN KEY (T3_FEATURETYPE1_ID) REFERENCES T3_FEATURETYPE1;

INSERT INTO T3_CODELIST1 (CODE, DESCRIPTION, NAME, ACTIVE_INDICATOR_LF, SOURCE_GCL) VALUES ('1', 'code1', '', 'Y', NULL);
INSERT INTO T3_CODELIST1 (CODE, DESCRIPTION, NAME, ACTIVE_INDICATOR_LF, SOURCE_GCL) VALUES ('2', 'code2', '', 'Y', NULL);
INSERT INTO T3_CODELIST1 (CODE, DESCRIPTION, NAME, ACTIVE_INDICATOR_LF, SOURCE_GCL) VALUES ('quote''me', 'code3', '', 'Y', NULL);
INSERT INTO T3_CODELIST2 (CODE, DESCRIPTION, NAME, ACTIVE_INDICATOR_LF, SOURCE_GCL) VALUES ('code''B', 'code''B', 'codeB definition', 'Y', NULL);
INSERT INTO T3_CODELIST2 (CODE, DESCRIPTION, NAME, ACTIVE_INDICATOR_LF, SOURCE_GCL) VALUES ('codeA', 'codeA', 'codeA''s definition', 'Y', NULL);
