CREATE TABLE T1_CLASS1 (

   TESTOBJECTIDENTIFIER INTEGER NOT NULL PRIMARY KEY,
   P1 SDO_GEOMETRY NOT NULL,
   P2 SDO_GEOMETRY NOT NULL,
   P3 SDO_GEOMETRY NOT NULL,
   P4 SDO_GEOMETRY NOT NULL,
   P5 SDO_GEOMETRY NOT NULL,
   P6 SDO_GEOMETRY NOT NULL,
   P7 SDO_GEOMETRY NOT NULL
);


INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1_CLASS1', 'P1', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', -2, 2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', -3.3, 3, 3)), 31467);
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1_CLASS1', 'P2', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', -2, 2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', -3.3, 3, 3)), 31467);
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1_CLASS1', 'P3', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', -2, 2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', -3.3, 3, 3)), 31467);
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1_CLASS1', 'P4', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', -2, 2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', -3.3, 3, 3)), 31467);
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1_CLASS1', 'P5', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', -2, 2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', -3.3, 3, 3)), 31467);
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1_CLASS1', 'P6', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', -2, 2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', -3.3, 3, 3)), 31467);
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1_CLASS1', 'P7', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', -2, 2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', -3.3, 3, 3)), 31467);

CREATE INDEX IDX_T1_CLASS1_P1 ON T1_CLASS1 (P1) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=point');
CREATE INDEX IDX_T1_CLASS1_P2 ON T1_CLASS1 (P2) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=line');
CREATE INDEX IDX_T1_CLASS1_P3 ON T1_CLASS1 (P3) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=polygon');
CREATE INDEX IDX_T1_CLASS1_P4 ON T1_CLASS1 (P4) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=multipoint');
CREATE INDEX IDX_T1_CLASS1_P5 ON T1_CLASS1 (P5) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=multiline');
CREATE INDEX IDX_T1_CLASS1_P6 ON T1_CLASS1 (P6) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=multipolygon');
CREATE INDEX IDX_T1_CLASS1_P7 ON T1_CLASS1 (P7) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=collection');
