CREATE TABLE T1C1P1 (

   T1_CLASS1_ID INTEGER NOT NULL,
   P1 SDO_GEOMETRY NOT NULL,
   PRIMARY KEY (T1_CLASS1_ID, P1)
);

CREATE TABLE T1C1P2 (

   T1_CLASS1_ID INTEGER NOT NULL,
   P2 SDO_GEOMETRY NOT NULL,
   PRIMARY KEY (T1_CLASS1_ID, P2)
);

CREATE TABLE T1_CLASS1 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   P4 SDO_GEOMETRY NOT NULL,
   P5 SDO_GEOMETRY NOT NULL,
   P6 SDO_GEOMETRY NOT NULL,
   P7 SDO_GEOMETRY NOT NULL
);

CREATE TABLE T1_CLASS1_P3 (

   T1_CLASS1_ID INTEGER NOT NULL,
   P3 SDO_GEOMETRY NOT NULL,
   PRIMARY KEY (T1_CLASS1_ID, P3)
);


ALTER TABLE T1C1P1 ADD CONSTRAINT FK_T1C1P1_T1_CLASS1_ID FOREIGN KEY (T1_CLASS1_ID) REFERENCES T1_CLASS1;
ALTER TABLE T1C1P2 ADD CONSTRAINT FK_T1C1P2_T1_CLASS1_ID FOREIGN KEY (T1_CLASS1_ID) REFERENCES T1_CLASS1;
ALTER TABLE T1_CLASS1_P3 ADD CONSTRAINT FK_T1_CLASS1_P3_T1_CLASS1_ID FOREIGN KEY (T1_CLASS1_ID) REFERENCES T1_CLASS1;

CREATE INDEX IDX_T1C1P1_P1 ON T1C1P1 (P1) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=point');
CREATE INDEX IDX_T1C1P2_P2 ON T1C1P2 (P2) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=line');
CREATE INDEX IDX_T1_CLASS1_P3_P3 ON T1_CLASS1_P3 (P3) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=polygon');
CREATE INDEX IDX_T1_CLASS1_P4 ON T1_CLASS1 (P4) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=multipoint');
CREATE INDEX IDX_T1_CLASS1_P5 ON T1_CLASS1 (P5) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=multiline');
CREATE INDEX IDX_T1_CLASS1_P6 ON T1_CLASS1 (P6) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=multipolygon');
CREATE INDEX IDX_T1_CLASS1_P7 ON T1_CLASS1 (P7) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=collection');

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1C1P1', 'P1', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', 2, -2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', 3.3, 3, -3)), 31467);
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1C1P2', 'P2', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', 2, -2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', 3.3, 3, -3)), 31467);
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1_CLASS1', 'P4', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', 2, -2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', 3.3, 3, -3)), 31467);
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1_CLASS1', 'P5', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', 2, -2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', 3.3, 3, -3)), 31467);
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1_CLASS1', 'P6', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', 2, -2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', 3.3, 3, -3)), 31467);
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1_CLASS1', 'P7', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', 2, -2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', 3.3, 3, -3)), 31467);
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('T1_CLASS1_P3', 'P3', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('dim1', -1, 1, 1.1), MDSYS.SDO_DIM_ELEMENT('dim2', 2, -2.2, 2), MDSYS.SDO_DIM_ELEMENT('dim3', 3.3, 3, -3)), 31467);
