CREATE TABLE T3_CODELIST1 (

   CODE VARCHAR2(50) NOT NULL PRIMARY KEY, -- Configured documentation of the 'CODE' column.
   DESCRIPTION VARCHAR2(255), -- Configured documentation for the 'DESCRIPTION' column, with special characters ,; = () and special keywords: size columnName columnDocumentation definition description ...
   CUSTOMCODESTATUSCLCOLUMN VARCHAR2(50), -- Configured documentation of the 'customCodeStatusCLColumn' column.
   CUSTOMNAMECODESTATUSNOTESCOLUM VARCHAR2(255), -- Configured documentation of the 'customNameCodeStatusNotesColumn' column.
   CUSTOMNAMECODESUPERCEDESCOLUMN VARCHAR2(50) -- Configured documentation of the 'customNameCodeSupercedesColumn' column.
);

CREATE TABLE T3_CODELIST2 (

   CODE VARCHAR2(50) NOT NULL PRIMARY KEY, -- Configured documentation of the 'CODE' column.
   DESCRIPTION VARCHAR2(255), -- Configured documentation for the 'DESCRIPTION' column, with special characters ,; = () and special keywords: size columnName columnDocumentation definition description ...
   CUSTOMCODESTATUSCLCOLUMN VARCHAR2(50), -- Configured documentation of the 'customCodeStatusCLColumn' column.
   CUSTOMNAMECODESTATUSNOTESCOLUM VARCHAR2(255), -- Configured documentation of the 'customNameCodeStatusNotesColumn' column.
   CUSTOMNAMECODESUPERCEDESCOLUMN VARCHAR2(50) -- Configured documentation of the 'customNameCodeSupercedesColumn' column.
);

CREATE TABLE T3_CODESTATUSCL (

   CODE VARCHAR2(50) NOT NULL PRIMARY KEY, -- Configured documentation of the 'CODE' column.
   DESCRIPTION VARCHAR2(255) -- Configured documentation for the 'DESCRIPTION' column, with special characters ,; = () and special keywords: size columnName columnDocumentation definition description ...
);

CREATE TABLE T3_FEATURETYPE1 (

   TESTOBJECTIDENTIFIER INTEGER NOT NULL PRIMARY KEY,
   PROPNUMCODE VARCHAR2(50) -- DEF: propNumCode definition; DESC: propNumCode description; EX: propNumCode example 1 propNumCode example 2; LB: propNumCode legal basis; DCS: propNumCode data capture statement 1 propNumCode data capture statement 2; PC: propNumCode primary code
);

CREATE TABLE T3_FEATURETYPE1_PROPALPCODE (

   T3_FEATURETYPE1TESTOBJECTIDENT INTEGER NOT NULL,
   T3_CODELIST2TESTOBJECTIDENTIFI VARCHAR2(50) NOT NULL, -- DEF: ; DESC: ; EX: ; LB: ; DCS: ; PC:
   PRIMARY KEY (T3_FEATURETYPE1TESTOBJECTIDENT, T3_CODELIST2TESTOBJECTIDENTIFI)
);


ALTER TABLE T3_CODELIST1 ADD CONSTRAINT FK_T3_CODEL_T3_CODES_CUSTOMCO FOREIGN KEY (CUSTOMCODESTATUSCLCOLUMN) REFERENCES T3_CODESTATUSCL;
ALTER TABLE T3_CODELIST2 ADD CONSTRAINT FK_T3_CODEL_T3_CODES_CUSTOMCO0 FOREIGN KEY (CUSTOMCODESTATUSCLCOLUMN) REFERENCES T3_CODESTATUSCL;
ALTER TABLE T3_FEATURETYPE1 ADD CONSTRAINT FK_T3_FEATU_T3_CODEL_PROPNUMC FOREIGN KEY (PROPNUMCODE) REFERENCES T3_CODELIST1;
ALTER TABLE T3_FEATURETYPE1_PROPALPCODE ADD CONSTRAINT FK_T3_FEATU_T3_CODEL_T3_CODEL FOREIGN KEY (T3_CODELIST2TESTOBJECTIDENTIFI) REFERENCES T3_CODELIST2;
ALTER TABLE T3_FEATURETYPE1_PROPALPCODE ADD CONSTRAINT FK_T3_FEATU_T3_FEATU_T3_FEATU FOREIGN KEY (T3_FEATURETYPE1TESTOBJECTIDENT) REFERENCES T3_FEATURETYPE1;

INSERT INTO T3_CODESTATUSCL (CODE, DESCRIPTION) VALUES ('valid', '');
INSERT INTO T3_CODESTATUSCL (CODE, DESCRIPTION) VALUES ('unknown', '');
INSERT INTO T3_CODESTATUSCL (CODE, DESCRIPTION) VALUES ('invalid', '');
INSERT INTO T3_CODELIST1 (CODE, DESCRIPTION, CUSTOMCODESTATUSCLCOLUMN, CUSTOMNAMECODESTATUSNOTESCOLUM, CUSTOMNAMECODESUPERCEDESCOLUMN) VALUES ('1', '', 'valid', NULL, NULL);
INSERT INTO T3_CODELIST1 (CODE, DESCRIPTION, CUSTOMCODESTATUSCLCOLUMN, CUSTOMNAMECODESTATUSNOTESCOLUM, CUSTOMNAMECODESUPERCEDESCOLUMN) VALUES ('2', '', 'valid', NULL, NULL);
INSERT INTO T3_CODELIST1 (CODE, DESCRIPTION, CUSTOMCODESTATUSCLCOLUMN, CUSTOMNAMECODESTATUSNOTESCOLUM, CUSTOMNAMECODESUPERCEDESCOLUMN) VALUES ('quote''me', '', 'valid', NULL, NULL);
INSERT INTO T3_CODELIST2 (CODE, DESCRIPTION, CUSTOMCODESTATUSCLCOLUMN, CUSTOMNAMECODESTATUSNOTESCOLUM, CUSTOMNAMECODESUPERCEDESCOLUMN) VALUES ('code''B', 'codeB definition', 'valid', NULL, NULL);
INSERT INTO T3_CODELIST2 (CODE, DESCRIPTION, CUSTOMCODESTATUSCLCOLUMN, CUSTOMNAMECODESTATUSNOTESCOLUM, CUSTOMNAMECODESUPERCEDESCOLUMN) VALUES ('codeA', 'codeA''s definition', 'valid', NULL, NULL);
