CREATE TABLE FEATURETYPE (

   ID INTEGER NOT NULL PRIMARY KEY,
   ATT1 NUMBER(5,2),
   ATT2 VARCHAR2(1024),
   ATT3 NUMBER(5,2) NOT NULL,
   ATT4 VARCHAR2(1024) NOT NULL
);


ALTER TABLE FEATURETYPE ADD CONSTRAINT FEATURETYPE_ATT1_CK CHECK (ATT1 IS NULL OR ATT1 IN (100.1, 100.2));
ALTER TABLE FEATURETYPE ADD CONSTRAINT FEATURETYPE_ATT2_CK CHECK (ATT2 IS NULL OR ATT2 IN ('X', 'Y'));
ALTER TABLE FEATURETYPE ADD CONSTRAINT FEATURETYPE_ATT3_CK CHECK (ATT3 IN (100.1, 100.2));
ALTER TABLE FEATURETYPE ADD CONSTRAINT FEATURETYPE_ATT4_CK CHECK (ATT4 IN ('X', 'Y'));
