:doctype: book
:encoding: utf-8
:lang: en
:toc: macro
:toc-title: Table of contents
:toclevels: 5

:toc-position: left

:appendix-caption: Annex

:numbered:
:sectanchors:
:sectnumlevels: 5


[[Enterprise_Architect_models]]
= Enterprise Architect models

Enterprise Architect (EA) is a product of SparxSystems Ltd, based in
Creswick, Australia, and is a software modeling tool designed primarily
for UML modeling.

The ShapeChange EA compatibility was developed on EA versions 7.0 and
7.1, and runs unchanged for later versions. ShapeChange has been used
with EA up to version 12.0.

A UML model stored in an EA repository can be processed by
ShapeChange, using the Java API of EA. There is no particular need to 
export the UML model to some format before processing the UML model.

NOTE: However, if the model content is fix, i.e. it does not change
anymore (e.g. in case of a particular published version of the model)
you may want to consider exporting the model to SCXML and to publish
this additional model format alongside the EA repository, for processing with ShapeChange.
For further details, see xref:./SCXML_models.adoc[this page].

To process Enterprise Architect models with ShapeChange, the steps to do so depend on the version of Java you'd like to use. If you have a 64bit machine, then we recommend using 64bit Java.

* 64bit Java:
** Copy the file SSJavaCOM64.dll located in _<EA installation folder>/Java API_ to <__Windows folder>/System32 (on a 64-bit machine).__
* 32 bit Java:
** Copy the file SSJavaCom.dll located in _<EA installation folder>/Java API_ to <__Windows folder>/System32__ (on a 32-bit machine) or to <__Windows folder>/SysWOW64__ (on a 64-bit machine).

NOTE: If you are searching for a 32bit JDK, take a look at the JDKs from https://adoptium.net/[Adoptium]. They provide 32bit OpenJDK for Java 8, 11, and later.