:doctype: book
:encoding: utf-8
:lang: en
:toc: macro
:toc-title: Table of contents
:toclevels: 5

:toc-position: left

:appendix-caption: Annex

:numbered:
:sectanchors:
:sectnumlevels: 5


[[ShapeChange_XML_models]]
= ShapeChange XML models

SCXML - short for 'ShapeChange XML' - is an XML format for storing UML model information, and is defined by https://github.com/ShapeChange/ShapeChange/blob/master/src/main/resources/schema/ShapeChangeExportedModel.xsd[this XML Schema]. 

NOTE: The model format has originally been developed to encode the ShapeChange internal representation of a UML model in XML, for exchange with the https://shapechange.github.io/ProfileManagementTool/[Profile Management Tool]. It has since been extended to serve a more general purpose as model format that can be processed by ShapeChange and other tools.

SCXML can be generated using the ShapeChange xref:../targets/Model_Export.adoc[Model export target], from any other model format that is read by ShapeChange (directly or via an extension).

SCXML is especially useful for cases in which the model does not change anymore - e.g. when a particular release of the model has been finalized and published - because it can dramatically increase the speed of reading the model (e.g. when compared to reading the model from an Enterprise Architect repository).
