CREATE TABLE FEATURETYPE (

   _ID INTEGER NOT NULL PRIMARY KEY,
   PROPPOINT SDO_GEOMETRY NOT NULL,
   PROPCURVE SDO_GEOMETRY NOT NULL
);


INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('FEATURETYPE', 'PROPCURVE', MDSYS.SDO_DIM_ARRAY(FIXME), 4979);
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('FEATURETYPE', 'PROPPOINT', MDSYS.SDO_DIM_ARRAY(FIXME), 4979);

CREATE INDEX IDX_FEATURETYPE_PROPCURVE ON FEATURETYPE (PROPCURVE) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=line');
CREATE INDEX IDX_FEATURETYPE_PX ON FEATURETYPE (PROPPOINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=point');
