CREATE TABLE FEATURETYPE1 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ROLEFT1B_FK INTEGER
);

CREATE TABLE FEATURETYPE1_ROLEFT1A (

   FEATURETYPE1_ID INTEGER NOT NULL,
   FEATURETYPE2_ID INTEGER NOT NULL,
   PRIMARY KEY (FEATURETYPE1_ID, FEATURETYPE2_ID)
);

CREATE TABLE FEATURETYPE2 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ROLEFT2B_FK INTEGER NOT NULL
);


ALTER TABLE FEATURETYPE1 ADD CONSTRAINT FK_FEATURETYPE1_ROLEFT1B_FK FOREIGN KEY (ROLEFT1B_FK) REFERENCES FEATURETYPE2 ON DELETE SET NULL;
ALTER TABLE FEATURETYPE1_ROLEFT1A ADD CONSTRAINT FK_FEATURETYPE1_ROLEFT1A_FEAT0 FOREIGN KEY (FEATURETYPE2_ID) REFERENCES FEATURETYPE2;
ALTER TABLE FEATURETYPE1_ROLEFT1A ADD CONSTRAINT FK_FEATURETYPE1_ROLEFT1A_FEATU FOREIGN KEY (FEATURETYPE1_ID) REFERENCES FEATURETYPE1;
ALTER TABLE FEATURETYPE2 ADD CONSTRAINT FK_FEATURETYPE2_ROLEFT2B_FK FOREIGN KEY (ROLEFT2B_FK) REFERENCES FEATURETYPE1;
