:doctype: book
:encoding: utf-8
:lang: en
:toc: macro
:toc-title: Table of contents
:toclevels: 5

:toc-position: left

:appendix-caption: Annex

:numbered:
:sectanchors:
:sectnumlevels: 5
:nofooter:

[[Code_List_Loader]]
= Code List Loader

(since v2.6.0)

[[Introduction]]
== Introduction

This transformation provides rules with which code lists contained in
the model can be populated with information. Typically, the codes of a
code list are managed outside of an application schema. That means that
even though the application schema content may be fixed in a specific
version of the schema, the codes of the code lists that are used by the
schema can vary. Externally managed code lists are typically modelled
without any codes.

A use case where the transformation is useful is encoding a code list in
a specific format, like an ISO 19139 code list dictionary. The
transformation loads the codes of a code list from its authoritative
source. Subsequent ShapeChange processes, like the
xref:../targets/dictionaries/ISO_19139_Codelist_Dictionary.adoc[ISO 19139
Codelist Dictionary target], can then derive a dictionary in the
required format. The same workflow can be used to update the dictionary
at any time.

[[Configuration]]
== Configuration

[[Class]]
=== Class

The class for this transformer implementation is
_de.interactive_instruments.shapechange.core.transformation.adding.CodeListLoader_

[[Transformation_Rules]]
=== Transformation Rules

[[rule-trf-cls-loadCodes]]
==== rule-trf-cls-loadCodes

This rule loads codes from authoritative code list sources into the
model. 

The transformation looks at each code list contained in the
schemas selected for processing. If the code list defines the source,
then the codes will be retrieved from the source and added to the code
list. 

NOTE: A code list which defines a code list source may already contain
codes (typically modeled as attributes). Loading codes from the source
may result in duplicate codes. By setting transformation parameter
<<removeExistingCodesBeforeLoading>> to true, the pre-existing codes 
can be removed before codes are loaded from the source. This behavior
is available since v4.0.0 of ShapeChange, and only applies to the
code lists for which a code list source is defined.

The source is defined by tagged value _codeListSource_, which
provides a link to a remote or local resource in a specific
representation. The representation is defined via tagged value
_codeListSourceRepresentation_ (or, since v4.0.0, using transformation 
parameter <<defaultCodeListSourceRepresentation>> as fallback). 
At the moment, the following representation is supported:

* Representation __application/x.iso639_2__:
** Definition: The CSV-based list of ISO 639-2 language codes, as
published by the
https://www.loc.gov/standards/iso639-2/ascii_8bits.html[Library of
Congress]. 
** Code retrieval details: The code name is the alpha-3
code (bibliographic, in case that both a bibliographic and a
terminologic code are available). The english name is used as the
definition and documentation of the code.
* Representation __application/x-re3gistry-json__:
** Definition: The JSON format for codelist encoding of the Re3gistry
implementation. Tested with the GDI-DE re3gistry instance of the
German mapping agencies.
** Code retrieval details: The code list source is a code list hosted
by a Re3gistry instance, in a specific register. The code list source
either is a URL or the path to a local JSON file (especially useful
for unit tests, or in cases where the Re3gistry is not readily available).
If a URL is given, and the URL does end with '.json', it is assumed 
that the URL directly links to the JSON representation in the 
desired language (see parameter <<re3gistryLang>>).
Otherwise, the URL is assumed to link to the base resource of the code list
in a specific register (which is determined from the URL), and 
`'/' + {code list name} + '.' + {value of parameter re3gistryLang} + '.json'`
is added to the source URL. If the code list source is a local JSON file,
parameter <<re3gistryRegister>> must be set, in order to identify the
relevant register.
From the JSON document, the objects in the member 
that represents the register are parsed:
*** The `definition/text` is set as definition of the code list - unless the
code list already has a non-empty definition.
*** For each item object within `containedItems`,
its `value` member is retrieved. It represents a particular code.
If the URL in `value/status/id` ends with `/valid` or `/retired`, the code is
loaded. Otherwise, it is ignored. Thus, only relevant codes are loaded from the 
registry. The value of member `value/CodeListValue_local_Id/text` is used as the initial value
for the new attribute that will be added to the code list to represent the code,
while the value of member `value/label/text` is used as attribute name.

Additional representations can be added in the future.

The tagged value _codeListSourceCharset_ can be used to define the
character set of the resource. This information is used to correctly
read the code list resource. If the tagged value is blank, then UTF-8 is
used by default. You can use one of the character sets supported by
Java. For further details, see the documentation of the Java class
https://docs.oracle.com/javase/8/docs/api/java/nio/charset/Charset.html[Charset]
and its method
https://docs.oracle.com/javase/8/docs/api/java/nio/charset/Charset.html#forName-java.lang.String-[forName(String
charsetName)].

[[Parameters]]
=== Parameters

[[defaultCodeListSourceRepresentation]]
==== defaultCodeListSourceRepresentation

(since v4.0.0)

+++Alias+++: _none_

+++Type+++: enum, one of 'application/x.iso639_2' and 'application/x-re3gistry-json'

+++Default value+++: _none_

+++Behavior+++

Default representation for code list sources.

+++Applies to Rule(s)+++

* <<rule-trf-cls-loadCodes>>


[[re3gistryLang]]
==== re3gistryLang

(since v4.0.0)

+++Alias+++: _none_

+++Type+++: string (should be a code for one of the languages supported by the relevant Re3gistry instance(s))

+++Default value+++: en

+++Behavior+++

Define the code of the language in which to retrieve code (list) metadata.


+++Applies to Rule(s)+++

* <<rule-trf-cls-loadCodes>>


[[re3gistryRegister]]
==== re3gistryRegister

(since v4.0.0)

+++Alias+++: _none_

+++Type+++: string

+++Default value+++: _none_

+++Behavior+++

Identifier of the register in which the code lists are located in the re3gistry.
Only relevant for cases in which the code list source is a local json file.
If the source is an HTTP URL, the register is automatically determined from
the URL.


+++Applies to Rule(s)+++

* <<rule-trf-cls-loadCodes>>


[[removeExistingCodesBeforeLoading]]
==== removeExistingCodesBeforeLoading

(since v4.0.0)

+++Alias+++: _none_

+++Type+++: boolean

+++Default value+++: false

+++Behavior+++

Set to true, in order for any pre-existing codes to be removed
from a code list before loading codes from the code list source
defined for that code list.

+++Applies to Rule(s)+++

* <<rule-trf-cls-loadCodes>>


[[Map_Entries]]
=== Map Entries

At the moment no map entries are defined for this transformation.

[[Advanced_Process_Configuration]]
=== Advanced Process Configuration

This transformation does not make use of the advanced process
configuration facility.

[[Configuration_Example]]
== Configuration Example

[source,xml,linenumbers]
----------
<Transformer class="de.interactive_instruments.shapechange.core.transformation.adding.CodeListLoader"
 id="TRF_CL_LOADER" input="IDENTITY" mode="enabled">
 <rules>
  <ProcessRuleSet name="cl_loader_rules">
   <rule name="rule-trf-cls-loadCodes"/>
  </ProcessRuleSet>
 </rules>
</Transformer>
----------
