:doctype: book
:encoding: utf-8
:lang: en
:toc: macro
:toc-title: Table of contents
:toclevels: 5

:toc-position: left

:appendix-caption: Annex

:numbered:
:sectanchors:
:sectnumlevels: 5
:nofooter:

[[First_Order_Logic_Constraint_Parser]]
= First Order Logic Constraint Parser

[[Introduction]]
== Introduction

[red]#(Beta)#

NOTE: [red]#Since v2.2.0, this transformation is deprecated.# Parsing and
validating constraints has become common transformer postprocessing
functionality (for further details, see
xref:./Common_Transformer_Functionality.adoc#Parsing_and_Validating_Constraints[here]).

Parses First Order Logic expressions from constraints contained in the
model. This is especially useful if constraints have been loaded via the
ConstraintLoader transformation (which does not parse the constraints).

NOTE: At the moment parsing is only supported for FOL constraints of
type 'SBVR'.

[[Configuration]]
== Configuration

The following sections specifiy the configuration options for this
transformation.

[[Class]]
=== Class

The class for this transformer implementation is
_de.interactive_instruments.shapechange.core.transformation.constraints.FolConstraintParsing_.

[[Parameters]]
=== Parameters

At the moment no specific parameters are defined for this
transformation.

[[Rules]]
=== Rules

At the moment no specific rules are defined for this transformation.

[[Map_Entries]]
=== Map Entries

At the moment no map entries are defined for this transformation.

[[Sample_Configuration]]
=== Sample Configuration

[source,xml,linenumbers]
----------
<Transformer
  class="de.interactive_instruments.shapechange.core.transformation.constraints.FolConstraintParsing"
  input="step2" id="step3" mode="enabled" />
----------
