:doctype: book
:encoding: utf-8
:lang: en
:toc: macro
:toc-title: Table of contents
:toclevels: 5

:toc-position: left

:appendix-caption: Annex

:numbered:
:sectanchors:
:sectnumlevels: 5
:nofooter:

[[Identity]]
= Identity

[[Introduction]]
== Introduction

The Identity transformation can be used to create a GenericModel
representation from a given input model. This can result in a
performance gain, if multiple targets and/or transformations are applied
on the input model, which may result in expensive operations - like
accessing an Enterprise Architect project file. If a GenericModel is
created and used for all subsequent processing (via targets and
transformations), such operations only need to be performed once.
Afterwards, the information is available in memory.

[[Configuration]]
== Configuration

The following sections specifiy the configuration options for the
Identitiy transformation.

[[Class]]
=== Class

The class for the Identity transformation implementation is
_de.interactive_instruments.shapechange.core.transformation.identity.IdentityTransform._

[[Parameters]]
=== Parameters

At the moment, no parameters are defined for the Identity
transformation.

[[Rules]]
=== Rules

At the moment, no rules are defined for the Identity transformation.

[[Map_Entries]]
=== Map Entries

At the moment, no map entries are defined for the Identity
transformation.

[[Sample_Configuration]]
=== Sample Configuration

[source,xml,linenumbers]
----------
<Transformer class="de.interactive_instruments.shapechange.core.transformation.identity.IdentityTransform" mode="enabled" id="GenMod"/>
----------
