:doctype: book
:encoding: utf-8
:lang: en
:toc: macro
:toc-title: Table of contents
:toclevels: 5

:toc-position: left

:appendix-caption: Annex

:numbered:
:sectanchors:
:sectnumlevels: 5
:nofooter:

[[Coretable]]
= Coretable

(since v4.1.0)

This target generates artefacts for applications
that use the so called 'coretable' database schema.


[[Configuration]]
== Configuration

[[Class]]
=== Class

The class for the target implementation is
_de.interactive_instruments.shapechange.core.target.coretable.Coretable_

[[Encoding_Rules]]
=== Encoding Rules

The following rules are supported by this target.

[[rule-coretable-all-notEncoded]]
==== rule-coretable-all-notEncoded

If __rule-coretable-all-notEncoded__ applies to an element 
of the application schema, then that element and all its 
components are not encoded and ignored by the target.

NOTE: How to define the encoding rule that applies to an 
application schema element is documented in more detail 
<<applying_specific_encoding_rule_to_model_element,here>>. 
The https://shapechange.net/resources/config/StandardRules.xml[ShapeChange configuration file StandardRules.xml] 
defines an encoding rule named "notEncoded", which includes 
__rule-coretable-all-notEncoded__. When StandardRules.xml 
is included in the configuration of the ldproxy target 
(typically using an xinclude XML element), then by setting 
tagged value _coretableEncodingRule_ to "notEncoded", one 
would achieve that that model element is not encoded and 
ignored by the target.


[[Parameters]]
=== Parameters

The parameters supported by this target are described in the following
sections.

[[appSchemaNameByTv]]
==== appSchemaNameByTv

(since 4.1.0)

Alias: _none_

Type: String

Default Value: _none_

Behavior: If set, the parameter provides the name of the
tagged value on the (main) application schema package, which
shall be used to populate column `appschema` in generated
coretable cascade rules. If the parameter is not set, or
the tagged value is blank (not set or has no non-empty value)
then the default behavior applies, i.e. to use the name
of the (main) application schema package as value for column
`appschema`.

Applies to Rule(s):

* _none - default behavior for generating cascade rules_

[[appSchemaVersionMajorMinorOnly]]
==== appSchemaVersionMajorMinorOnly

(since 4.1.0)

Alias: _none_

Type: Boolean

Default Value: false

Behavior: Reduces the version value of the (main) application
schema - to be set as value for column `version` in cascade rules - 
to the substring before the second occurrence of character '.'.
This effectively reduces a version to the major and minor part
(e.g. '1.22.3' is reduced to '1.22').

Applies to Rule(s):

* _none - default behavior for generating cascade rules_

[[dbSchemaName]]
==== dbSchemaName

(since 4.1.0)

Alias: _none_

Type: String

Default Value: public

Behavior: Identifies the name of the database schema in which the 
coretable as well as related tables and functions are located.

Applies to Rule(s):

* _none - default behavior_

[[defaultEncodingRule]]
==== defaultEncodingRule

Alias: _none_

Type: String

Default Value: _none_

Behavior:

The identifier of the default encoding rule governing the derivation of
coretable artefacts.

Applies to Rule(s):

* _none - default behavior_

[[generateCascadeRules]]
==== generateCascadeRules

(since 4.1.0)

Alias: _none_

Type: Boolean

Default Value: _false_

Behavior:

If true, then a .sql file with SELECT statements for adding
cascade rules will be generated by the target. The filename is
determined as follows: `{value of target parameter outputFilename}-cascade-rules.sql`

At first, feature types, object types, and mixin types from the
schemas selected for processing are collected.

Then, associations between these classes are identified, in which a 
navigable association role has tag `existentiallyDependentPart` with boolean 
value 'true'. That association role references the existentially dependent 
part in a whole-part relationship (where a part may also be shared by 
multiple wholes).

For each such association, the non-abstract (sub-)classes on both
end(s) are determined (thereby excluding mixins). A cascade rule is added
for each combination.

In order to check the whole-part-relationships for invalid loops
(i.e., a reflexive association) or cycles, a directed graph is created 
from the cascade rules. Then a check for loops and cycles
is conducted. If one is detected, an error is logged, 
together with information about the loops and cycles, and no
cascade rules are written. Otherwise, the longest path (from root
to leafs) within the trees that each node in the graph spans is 
computed and logged (length as well as an example path in the 
form of the association roles that make up the edges within the path).

Applies to Rule(s):

* _none - default behavior_

[[generateInsertStatements]]
==== generateInsertStatements

(since 4.1.0)

Alias: _none_

Type: Boolean

Default Value: _false_

Behavior:

If true, then cascade rules are created as INSERT statements
for table `cascade_delete_config`. Otherwise, the default behavior
for generating cascade rules applies, which is to generate 
SELECT statements for calling function `add_cascade_rule`.

Applies to Rule(s):

* _none - default behavior for generating cascade rules_

[[outputDirectory]]
==== outputDirectory

Alias: _none_

Type: String

Default Value: _the current run directory_

Behavior:

The path to the folder in which output files will be created.

Applies to Rule(s):

* _none - default behavior_

[[outputFilename]]
==== outputFilename

Required / Optional: Optional

Type: String

Default Value: coretable

Explanation: The name (prefix, i.e. without file extension) 
that shall be used when creating output files.

Applies to Rule(s): none – default behavior

[[Map_Entries]]
=== Map Entries

At the moment, no specific map entries have been defined for this
target.

[[Sample_Configuration]]
=== Sample Configuration

[source,xml,linenumbers]
----------
<Target class="de.interactive_instruments.shapechange.core.target.coretable.Coretable" mode="enabled">
  <targetParameter name="outputDirectory" value="testResults/coretable/cascadeRules"/>
  <targetParameter name="sortedOutput" value="true"/>
  <targetParameter name="generateCascadeRules" value="true"/>
  <targetParameter name="dbSchemaName" value="test"/>
  <xi:include href="./config/StandardRules.xml"/>
</Target>
----------

[[coretable_encodingrules]]
== Encoding Rules

[[applying_specific_encoding_rule_to_model_element]]
For some application schemas, it is useful to know that different encoding rules can be applied to the subpackages, classes, and properties defined by the schema. Typically, a single encoding rule applies to all application schema elements. In ShapeChange, that rule is identified by setting the target parameter _defaultEncodingRule_, with the unique name defined for the encoding rule in the target configuration. The target configuration, however, can contain multiple encoding rules (with different names). By setting tagged value _coretableEncodingRule_ on an application schema element, using the name of another encoding rule, the model element will be encoded as defined by that rule.