:doctype: book
:encoding: utf-8
:lang: en
:toc: macro
:toc-title: Table of contents
:toclevels: 5

:toc-position: left

:appendix-caption: Annex

:numbered:
:sectanchors:
:sectnumlevels: 5
:nofooter:

[[Coretable]]
= Coretable

(since v4.1.0)

This target generates artefacts for applications
that use the so called 'coretable' database schema.


[[Configuration]]
== Configuration

[[Class]]
=== Class

The class for the target implementation is
_de.interactive_instruments.shapechange.core.target.coretable.Coretable_

[[Encoding_Rules]]
=== Encoding Rules

The following rules are supported by this target.

[[rule-coretable-all-notEncoded]]
==== rule-coretable-all-notEncoded

If __rule-coretable-all-notEncoded__ applies to an element 
of the application schema, then that element and all its 
components are not encoded and ignored by the target.

NOTE: How to define the encoding rule that applies to an 
application schema element is documented in more detail 
<<applying_specific_encoding_rule_to_model_element,here>>. 
The https://shapechange.net/resources/config/StandardRules.xml[ShapeChange configuration file StandardRules.xml] 
defines an encoding rule named "notEncoded", which includes 
__rule-coretable-all-notEncoded__. When StandardRules.xml 
is included in the configuration of the ldproxy target 
(typically using an xinclude XML element), then by setting 
tagged value _coretableEncodingRule_ to "notEncoded", one 
would achieve that that model element is not encoded and 
ignored by the target.


[[Parameters]]
=== Parameters

The parameters supported by this target are described in the following
sections.

[[appSchemaNameByTv]]
==== appSchemaNameByTv

(since 4.1.0)

Alias: _none_

Type: String

Default Value: _none_

Behavior: If set, the parameter provides the name of the
tagged value on the (main) application schema package, which
shall be used to populate column `appschema` in generated
coretable navigable role configuration entries. If the parameter 
is not set, or the tagged value is blank (not set or has no 
non-empty value) then the default behavior applies, i.e. to use the name
of the (main) application schema package as value for column
`appschema`.

Applies to Rule(s):

* _none - default behavior for generating navigable role configuration entries_

[[appSchemaVersionMajorMinorOnly]]
==== appSchemaVersionMajorMinorOnly

(since 4.1.0)

Alias: _none_

Type: Boolean

Default Value: false

Behavior: Reduces the version value of the (main) application
schema - to be set as value for column `version` in navigable role configuration entries - 
to the substring before the second occurrence of character '.'.
This effectively reduces a version to the major and minor part
(e.g. '1.22.3' is reduced to '1.22').

Applies to Rule(s):

* _none - default behavior for generating navigable role configuration entries_

[[dbSchemaName]]
==== dbSchemaName

(since 4.1.0)

Alias: _none_

Type: String

Default Value: public

Behavior: Identifies the name of the database schema in which the 
coretable as well as related tables and functions are located.

Applies to Rule(s):

* _none - default behavior_

[[defaultEncodingRule]]
==== defaultEncodingRule

Alias: _none_

Type: String

Default Value: _none_

Behavior:

The identifier of the default encoding rule governing the derivation of
coretable artefacts.

Applies to Rule(s):

* _none - default behavior_

[[generateNavigableRolesConfig]]
==== generateNavigableRolesConfig

(since 4.1.0)

Alias: _none_

Type: Boolean

Default Value: _false_

Behavior:

If true, then a .sql file with SELECT or INSERT statements for adding
navigable role configuration entries will be generated by the target. The filename is
determined as follows: `{value of target parameter outputFilename}-navigable-roles.sql`

NOTE: Whether SELECT or INSERT statements are generated is controlled
via target parameter <<generateInsertStatements>>.

At first, feature types, object types, and mixin types from the
schemas selected for processing are collected. Then, associations 
between these classes are identified. Navigable role configuration
entries are created for each navigable role of such an association:
one entry per combination of non-abstract (sub-)classes on both ends
of the navigable role (thereby excluding mixins).

A navigable role configuration entry consists of the following
information items:

* source_featuretype: (non-abstract) feature type that has the 
navigable role (navigation origin)
* navigable_role: name of the navigable role (which, in the
coretable, can be matched against column `rel` (forward) or 
`rel_inv` (inverse) of table `refs` in the coretable database
* target_featuretype: (non-abstract) feature type reached via 
the role (navigation destination)
* appschema: Application schema shared by source and target objects
* appschema_version: Application schema version shared by source 
and target objects
* rel_direction: Direction in which the navigable role is
represented in table `refs` of the coretable database: 
** `forward` (source feature id in column `base_id`, target feature id in column `related_id`, role name in column `rel`)
** `inverse` (source feature id in column `related_id`, target feature id in column `base_id`, role name in column `rel_inv`)
* dependent_part: Identifies which endpoint is the 
existentially-dependent part. This information is used for 
cascade delete and orphan detection. Ownership relations are 
defined by tag `existentialDependencyType` on navigable association 
roles - either with value `owner` to identify the owner / whole, 
or `part` to identify the owned / part object. Note that a part 
may also be shared by multiple wholes. This tagging supports cases 
of uni-directional associations where the navigable role references
the owner or the part of the ownership relation. Note that for a
bi-directional association, it is invalid to define the tag
with same value on both association roles. Possible values for 
dependent_part are:
** `target` = source feature owns target feature (source is whole, target is part)
** `source` = target feature owns source feature (target is whole, source is part)
** NULL = the navigable role is not part of an ownership relation

NOTE: In this context, the terms `source` and `target` mean the features
involved in the relationship defined by the navigable role: `source` is
the the feature that has the association role, `target` is the feature
that is the value type of the association role, i.e. the object 
referenced by the role. These terms are NOT the same as and therefore NOT
to be confused with source and target roles within Enterprise Architect model terminology.

In order to check the ownership relations for invalid loops
(i.e., a reflexive association) or cycles, a directed graph is created. 
Then a check for loops and cycles is conducted.
If one is detected, an error is logged, together with information 
about the loops and cycles, and no navigable role configuration 
entries are written. Otherwise, the longest path (from root
to leafs) within the trees that each node in the graph spans is 
computed and logged (length as well as an example path in the 
form of the association roles that make up the edges within the path).

Applies to Rule(s):

* _none - default behavior_

[[generateInsertStatements]]
==== generateInsertStatements

(since 4.1.0)

Alias: _none_

Type: Boolean

Default Value: _false_

Behavior:

If true, then navigable role configuration entries are created as 
INSERT statements for table `navigable_roles_config`. Otherwise, the 
default behavior for generating navigable role configuration entries 
applies, which is to generate SELECT statements for calling 
function `add_navigable_role`.

Applies to Rule(s):

* _none - default behavior for generating navigable role configuration entries_

[[outputDirectory]]
==== outputDirectory

Alias: _none_

Type: String

Default Value: _the current run directory_

Behavior:

The path to the folder in which output files will be created.

Applies to Rule(s):

* _none - default behavior_

[[outputFilename]]
==== outputFilename

Required / Optional: Optional

Type: String

Default Value: coretable

Explanation: The name (prefix, i.e. without file extension) 
that shall be used when creating output files.

Applies to Rule(s): none – default behavior

[[Map_Entries]]
=== Map Entries

At the moment, no specific map entries have been defined for this
target.

[[Sample_Configuration]]
=== Sample Configuration

[source,xml,linenumbers]
----------
<Target class="de.interactive_instruments.shapechange.core.target.coretable.Coretable" mode="enabled">
  <targetParameter name="outputDirectory" value="testResults/coretable/navigableRolesConfig"/>
  <targetParameter name="sortedOutput" value="true"/>
  <targetParameter name="generateNavigableRolesConfig" value="true"/>
  <targetParameter name="dbSchemaName" value="test"/>
  <xi:include href="./config/StandardRules.xml"/>
</Target>
----------

[[coretable_encodingrules]]
== Encoding Rules

[[applying_specific_encoding_rule_to_model_element]]
For some application schemas, it is useful to know that different encoding rules can be applied to the subpackages, classes, and properties defined by the schema. Typically, a single encoding rule applies to all application schema elements. In ShapeChange, that rule is identified by setting the target parameter _defaultEncodingRule_, with the unique name defined for the encoding rule in the target configuration. The target configuration, however, can contain multiple encoding rules (with different names). By setting tagged value _coretableEncodingRule_ on an application schema element, using the name of another encoding rule, the model element will be encoded as defined by that rule.