CREATE TABLE CODELIST1 (

   NAME CLOB NOT NULL PRIMARY KEY,
   DOCUMENTATION CLOB
);

CREATE TABLE FEATURETYPE1 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ATT INTEGER NOT NULL,
   CL_FK CLOB NOT NULL
);

CREATE TABLE FEATURETYPE1_DT (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ATT1 INTEGER NOT NULL,
   ATT2 VARCHAR2(1024) NOT NULL,
   FEATURETYPE1_ID INTEGER NOT NULL
);

CREATE TABLE FEATURETYPE1_ROLEFT1TOFT2 (

   FEATURETYPE1_ID INTEGER NOT NULL,
   FEATURETYPE2_ID INTEGER NOT NULL,
   PRIMARY KEY (FEATURETYPE1_ID, FEATURETYPE2_ID)
);

CREATE TABLE FEATURETYPE2 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ROLEFT2TOFT1B_FK INTEGER NOT NULL
);

CREATE TABLE FEATURETYPE2_ATT (

   FEATURETYPE2_ID INTEGER NOT NULL,
   ATT INTEGER NOT NULL,
   PRIMARY KEY (FEATURETYPE2_ID, ATT)
);

CREATE TABLE FEATURETYPE2_CL (

   FEATURETYPE2_ID INTEGER NOT NULL,
   CODELIST1_ID CLOB NOT NULL,
   PRIMARY KEY (FEATURETYPE2_ID, CODELIST1_ID)
);

CREATE TABLE FEATURETYPE2_DT (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ATT1 INTEGER NOT NULL,
   ATT2 VARCHAR2(1024) NOT NULL,
   FEATURETYPE2_ID INTEGER NOT NULL
);


ALTER TABLE FEATURETYPE1 ADD CONSTRAINT FK_FEATURETYPE1_CL_FK FOREIGN KEY (CL_FK) REFERENCES CODELIST1 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE FEATURETYPE1_DT ADD CONSTRAINT FK_FEATURETYPE1_DT_FEATURETYPE FOREIGN KEY (FEATURETYPE1_ID) REFERENCES FEATURETYPE1 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE FEATURETYPE1_ROLEFT1TOFT2 ADD CONSTRAINT FK_FEATURETYPE1_ROLEFT1TOFT2_0 FOREIGN KEY (FEATURETYPE2_ID) REFERENCES FEATURETYPE2 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE FEATURETYPE1_ROLEFT1TOFT2 ADD CONSTRAINT FK_FEATURETYPE1_ROLEFT1TOFT2_F FOREIGN KEY (FEATURETYPE1_ID) REFERENCES FEATURETYPE1 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE FEATURETYPE2 ADD CONSTRAINT FK_FEATURETYPE2_ROLEFT2TOFT1B_ FOREIGN KEY (ROLEFT2TOFT1B_FK) REFERENCES FEATURETYPE1 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE FEATURETYPE2_ATT ADD CONSTRAINT FK_FEATURETYPE2_ATT_FEATURETYP FOREIGN KEY (FEATURETYPE2_ID) REFERENCES FEATURETYPE2 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE FEATURETYPE2_CL ADD CONSTRAINT FK_FEATURETYPE2_CL_CODELIST1_I FOREIGN KEY (CODELIST1_ID) REFERENCES CODELIST1 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE FEATURETYPE2_CL ADD CONSTRAINT FK_FEATURETYPE2_CL_FEATURETYPE FOREIGN KEY (FEATURETYPE2_ID) REFERENCES FEATURETYPE2 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE FEATURETYPE2_DT ADD CONSTRAINT FK_FEATURETYPE2_DT_FEATURETYPE FOREIGN KEY (FEATURETYPE2_ID) REFERENCES FEATURETYPE2 DEFERRABLE INITIALLY IMMEDIATE;

INSERT INTO CODELIST1 (NAME, DOCUMENTATION) VALUES ('codeA', '');
INSERT INTO CODELIST1 (NAME, DOCUMENTATION) VALUES ('codeB', '');
