CREATE TABLE CODELIST (

   NAME VARCHAR2(50 BYTE) NOT NULL PRIMARY KEY,
   DOCUMENTATION CLOB
);

CREATE TABLE DATATYPE (

   _ID INTEGER NOT NULL PRIMARY KEY,
   DTPROP CLOB NOT NULL,
   DTPROP2 VARCHAR2(50 BYTE) NOT NULL,
   DTPROP3 CLOB NOT NULL
);

CREATE TABLE FEATURETYPE1 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   P1 VARCHAR2(30 BYTE) NOT NULL,
   P4 INTEGER NOT NULL,
   P5 VARCHAR2(20 CHAR) NOT NULL,
   P6 VARCHAR2 NOT NULL,
   P7 VARCHAR2(6 BYTE) NOT NULL
);

CREATE TABLE FEATURETYPE1_P2 (

   FEATURETYPE1_ID INTEGER NOT NULL,
   P2 CLOB NOT NULL,
   PRIMARY KEY (FEATURETYPE1_ID, P2)
);

CREATE TABLE FEATURETYPE1_P3 (

   FEATURETYPE1_ID INTEGER NOT NULL,
   DATATYPE_ID INTEGER NOT NULL,
   PRIMARY KEY (FEATURETYPE1_ID, DATATYPE_ID)
);


ALTER TABLE FEATURETYPE1_P2 ADD CONSTRAINT FK_FEATURETYPE1_P2_FEATURETYPE FOREIGN KEY (FEATURETYPE1_ID) REFERENCES FEATURETYPE1;
ALTER TABLE FEATURETYPE1_P3 ADD CONSTRAINT FK_FEATURETYPE1_P3_DATATYPE_ID FOREIGN KEY (DATATYPE_ID) REFERENCES DATATYPE;
ALTER TABLE FEATURETYPE1_P3 ADD CONSTRAINT FK_FEATURETYPE1_P3_FEATURETYPE FOREIGN KEY (FEATURETYPE1_ID) REFERENCES FEATURETYPE1;

INSERT INTO CODELIST (NAME, DOCUMENTATION) VALUES ('code1', '');
INSERT INTO CODELIST (NAME, DOCUMENTATION) VALUES ('code2', '');
