CREATE TABLE FEATURETYPE1 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ROLEFT1B_FK INTEGER,
   ROLEFT1C_FK INTEGER NOT NULL,
   ROLEFT1E_FK INTEGER
);

CREATE TABLE FEATURETYPE1_ROLEFT1A (

   FEATURETYPE1_ID INTEGER NOT NULL,
   FEATURETYPE2_ID INTEGER NOT NULL,
   PRIMARY KEY (FEATURETYPE1_ID, FEATURETYPE2_ID)
);

CREATE TABLE FEATURETYPE1_ROLEFT1D (

   FEATURETYPE1_ID INTEGER NOT NULL,
   FEATURETYPE2_ID INTEGER NOT NULL,
   PRIMARY KEY (FEATURETYPE1_ID, FEATURETYPE2_ID)
);

CREATE TABLE FEATURETYPE2 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ROLEFT2B_FK INTEGER NOT NULL,
   ROLEFT2D_FK INTEGER NOT NULL
);

CREATE TABLE FEATURETYPE3 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ATTSINGLEVALUE VARCHAR2(1024) NOT NULL
);

CREATE TABLE FEATURETYPE3_ATTDATATYPE (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ATT1 INTEGER NOT NULL,
   ATT2 VARCHAR2(1024) NOT NULL,
   FEATURETYPE3_ID INTEGER NOT NULL
);

CREATE TABLE FEATURETYPE3_ATTMULTIVALUE (

   FEATURETYPE3_ID INTEGER NOT NULL,
   ATTMULTIVALUE INTEGER NOT NULL,
   PRIMARY KEY (FEATURETYPE3_ID, ATTMULTIVALUE)
);


ALTER TABLE FEATURETYPE1 ADD CONSTRAINT FK_FEATURETYPE1_ROLEFT1B_FK FOREIGN KEY (ROLEFT1B_FK) REFERENCES FEATURETYPE2 ON DELETE SET NULL;
ALTER TABLE FEATURETYPE1 ADD CONSTRAINT FK_FEATURETYPE1_ROLEFT1C_FK FOREIGN KEY (ROLEFT1C_FK) REFERENCES FEATURETYPE2 ON DELETE CASCADE;
ALTER TABLE FEATURETYPE1 ADD CONSTRAINT FK_FEATURETYPE1_ROLEFT1E_FK FOREIGN KEY (ROLEFT1E_FK) REFERENCES FEATURETYPE2 ON DELETE CASCADE;
ALTER TABLE FEATURETYPE1_ROLEFT1A ADD CONSTRAINT FK_FEATURETYPE1_ROLEFT1A_FEAT0 FOREIGN KEY (FEATURETYPE2_ID) REFERENCES FEATURETYPE2;
ALTER TABLE FEATURETYPE1_ROLEFT1A ADD CONSTRAINT FK_FEATURETYPE1_ROLEFT1A_FEATU FOREIGN KEY (FEATURETYPE1_ID) REFERENCES FEATURETYPE1;
ALTER TABLE FEATURETYPE1_ROLEFT1D ADD CONSTRAINT FK_FEATURETYPE1_ROLEFT1D_FEAT0 FOREIGN KEY (FEATURETYPE2_ID) REFERENCES FEATURETYPE2 ON DELETE CASCADE;
ALTER TABLE FEATURETYPE1_ROLEFT1D ADD CONSTRAINT FK_FEATURETYPE1_ROLEFT1D_FEATU FOREIGN KEY (FEATURETYPE1_ID) REFERENCES FEATURETYPE1 ON DELETE CASCADE;
ALTER TABLE FEATURETYPE2 ADD CONSTRAINT FK_FEATURETYPE2_ROLEFT2B_FK FOREIGN KEY (ROLEFT2B_FK) REFERENCES FEATURETYPE1;
ALTER TABLE FEATURETYPE2 ADD CONSTRAINT FK_FEATURETYPE2_ROLEFT2D_FK FOREIGN KEY (ROLEFT2D_FK) REFERENCES FEATURETYPE1 ON DELETE CASCADE;
ALTER TABLE FEATURETYPE3_ATTDATATYPE ADD CONSTRAINT FK_FEATURETYPE3_ATTDATATYPE_FE FOREIGN KEY (FEATURETYPE3_ID) REFERENCES FEATURETYPE3 ON DELETE CASCADE;
ALTER TABLE FEATURETYPE3_ATTMULTIVALUE ADD CONSTRAINT FK_FEATURETYPE3_ATTMULTIVALUE_ FOREIGN KEY (FEATURETYPE3_ID) REFERENCES FEATURETYPE3 ON DELETE CASCADE;
