:doctype: book
:encoding: utf-8
:lang: en
:toc: macro
:toc-title: Table of contents
:toclevels: 5

:toc-position: left

:appendix-caption: Annex

:numbered:
:sectanchors:
:sectnumlevels: 5

[[Release_Notes]]
= Release Notes

This page provides information on the ShapeChange releases. An overview
is provided first, followed by a list of detailed notes for each
release. The list of currently known issues is available on
https://github.com/ShapeChange/ShapeChange/issues[GitHub].

[[Overview]]
== Overview

The ShapeChange {project-version} release package can be downloaded https://shapechange.net/resources/dist/net/shapechange/ShapeChange/{project-version}/ShapeChange-{project-version}.zip[here].

Additional information, including dependencies:

* Java Version: Java 11 (tested with 64 bit)
* Tested EA Version(s): EA 16.1 (both 32 and 64 bit)
** NOTE: This field specifies the versions of EA with which the given
ShapeChange release has been developed and tested. The release will in
most cases also work with other versions of EA (especially: versions
prior to the specified version), because the EA API as well as the
interfaces used by ShapeChange are often - but not always - backwards
compatible. However, versions of EA prior to EA 16.0 should not be used.
* EA API included in distribution: EA 16.1.1628
** NOTE: If you are using a different version of EA and experience
issues when executing ShapeChange, you can try exchanging the eaapi.jar
in the "lib" folder with the one provided by your version of EA (the
.jar file can be found in "\{EA installation directory}/Java API"). Make
sure to rename your eaapi.jar to the one you wish to replace, otherwise
ShapeChange-internal links to the jar (especially in the manifest of the
ShapeChange JAR file) may be broken.
* Saxon JAR used: Saxon-HE-10.2.jar
** NOTE: Identifies the version of the Saxon HE jar that is used by the
ShapeChange release. If you plan to create
xref:../targets/feature catalogue/Feature_Catalogue.adoc[feature catalogues]
or to apply
xref:../targets/Output_Targets.adoc#Apply_XSL_Transformation[XSL
transformations] to output files and would like to use Saxon as XSLT
processor, then download that version of the Saxon HE jar from the
https://mvnrepository.com/artifact/net.sf.saxon/Saxon-HE[official maven
repository] and copy it to the lib folder of your ShapeChange
distribution.

[[Changelog]]
== Changelog

Since v2.5.0, a log with all changes is available in our
https://github.com/ShapeChange/ShapeChange/blob/master/CHANGELOG.md[GitHub
repository].