CREATE TABLE ASOTABLE (

   FEATURETYPE1_ID INTEGER NOT NULL,
   FEATURETYPE2_ID INTEGER NOT NULL,
   PRIMARY KEY (FEATURETYPE1_ID, FEATURETYPE2_ID)
);

CREATE TABLE FEATURETYPE1 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ROLEFT1B_FK INTEGER,
   PROPDATE DATE NOT NULL,
   PROPENUM CLOB NOT NULL,
   PROPUNIQUE CLOB NOT NULL
);

CREATE TABLE FEATURETYPE2 (

   _ID INTEGER NOT NULL PRIMARY KEY
);


ALTER TABLE ASOTABLE ADD CONSTRAINT FK_ASOTABLE_FEATURETYPE1_ID FOREIGN KEY (FEATURETYPE1_ID) REFERENCES FEATURETYPE1;
ALTER TABLE ASOTABLE ADD CONSTRAINT FK_ASOTABLE_FEATURETYPE2_ID FOREIGN KEY (FEATURETYPE2_ID) REFERENCES FEATURETYPE2;
ALTER TABLE FEATURETYPE1 ADD CONSTRAINT FEATURETYPE1_PROPENUM_CK CHECK (PROPENUM IN ('enum1', 'enum2'));
ALTER TABLE FEATURETYPE1 ADD CONSTRAINT FEATURETYPE1_PX_CK CHECK (TO_CHAR(PROPDATE, 'HH24:MI:SS') = '00:00:00');
ALTER TABLE FEATURETYPE1 ADD CONSTRAINT FK_FEATURETYPE1_ROLEFT1B_FK FOREIGN KEY (ROLEFT1B_FK) REFERENCES FEATURETYPE2;
ALTER TABLE FEATURETYPE1 ADD CONSTRAINT UK_FEATURETYPE1_PROPUNIQUE UNIQUE (PROPUNIQUE);
