CREATE TABLE CODELISTCAT1 (

   NAME CLOB NOT NULL PRIMARY KEY,
   DOCUMENTATION CLOB
);

CREATE TABLE CODELISTCAT2 (

   NAME CLOB NOT NULL PRIMARY KEY,
   DOCUMENTATION CLOB
);

CREATE TABLE CODELISTCAT3 (

   NAME CLOB NOT NULL PRIMARY KEY,
   DOCUMENTATION CLOB
);

CREATE TABLE CODELISTCAT4 (

   NAME CLOB NOT NULL PRIMARY KEY,
   DOCUMENTATION CLOB
);

CREATE TABLE FEATURETYPE (

   ID INTEGER NOT NULL PRIMARY KEY,
   PCODE1 CLOB NOT NULL,
   PCODE2 CLOB NOT NULL,
   PCODE3 CLOB NOT NULL,
   PCODE4 CLOB NOT NULL,
   PGEOM1 SDO_GEOMETRY NOT NULL,
   PGEOM2 SDO_GEOMETRY NOT NULL
);


INSERT INTO CODELISTCAT1 (NAME, DOCUMENTATION) VALUES ('code1A', '');
INSERT INTO CODELISTCAT1 (NAME, DOCUMENTATION) VALUES ('code1B', '');
INSERT INTO CODELISTCAT4 (NAME, DOCUMENTATION) VALUES ('code4A', '');
INSERT INTO CODELISTCAT4 (NAME, DOCUMENTATION) VALUES ('code4B', '');
