<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:ext="http://example.org/shapechange/schema/external"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo"
        xmlns:t="http://example.org/shapechange/schema/test"
        elementFormDefault="qualified"
        targetNamespace="http://example.org/shapechange/schema/test"
        version="1.0">
   <import namespace="http://example.org/shapechange/schema/external"/>
   <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo"
           schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
   <import namespace="http://www.opengis.net/gml/3.2"
           schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
   <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
   <element name="FeatureType1"
            substitutionGroup="gml:AbstractFeature"
            type="t:FeatureType1Type"/>
   <complexType name="FeatureType1Type">
      <complexContent>
         <extension base="gml:AbstractFeatureType">
            <sequence>
               <element name="refRoleSource" type="t:FeatureType1PropertyType">
                  <annotation>
                     <appinfo>
                        <reversePropertyName xmlns="http://www.opengis.net/gml/3.2">t:refRoleTarget</reversePropertyName>
                        <sc:taggedValue tag="reversePropertyName">refRoleTarget</sc:taggedValue>
                        <sc:taggedValue tag="sourceOrTarget">source</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="refRoleTarget" type="t:FeatureType1PropertyType">
                  <annotation>
                     <appinfo>
                        <reversePropertyName xmlns="http://www.opengis.net/gml/3.2">t:refRoleSource</reversePropertyName>
                        <sc:taggedValue tag="reversePropertyName">refRoleSource</sc:taggedValue>
                        <sc:taggedValue tag="sourceOrTarget">target</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="aroleTarget" type="t:FeatureType2PropertyType">
                  <annotation>
                     <appinfo>
                        <reversePropertyName xmlns="http://www.opengis.net/gml/3.2">t:aroleSource</reversePropertyName>
                        <sc:taggedValue tag="reversePropertyName">aroleSource</sc:taggedValue>
                        <sc:taggedValue tag="sourceOrTarget">target</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
               <element name="targetFT1Ext" type="ext:FeatureTypeExtPropertyType">
                  <annotation>
                     <appinfo>
                        <reversePropertyName xmlns="http://www.opengis.net/gml/3.2">ext:sourceFT1Ext</reversePropertyName>
                        <sc:taggedValue tag="reversePropertyName">sourceFT1Ext</sc:taggedValue>
                        <sc:taggedValue tag="sourceOrTarget">target</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
            <element name="aroleUniDirectionalAssociation" type="t:FeatureType2PropertyType"/>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="FeatureType1PropertyType">
      <sequence minOccurs="0">
         <element ref="t:FeatureType1"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
   <element name="FeatureType2"
            substitutionGroup="gml:AbstractFeature"
            type="t:FeatureType2Type"/>
   <complexType name="FeatureType2Type">
      <complexContent>
         <extension base="gml:AbstractFeatureType">
            <sequence>
               <element name="aroleSource" type="t:FeatureType1PropertyType">
                  <annotation>
                     <appinfo>
                        <reversePropertyName xmlns="http://www.opengis.net/gml/3.2">t:aroleTarget</reversePropertyName>
                        <sc:taggedValue tag="reversePropertyName">aroleTarget</sc:taggedValue>
                        <sc:taggedValue tag="sourceOrTarget">source</sc:taggedValue>
                     </appinfo>
                  </annotation>
               </element>
            </sequence>
         </extension>
      </complexContent>
   </complexType>
   <complexType name="FeatureType2PropertyType">
      <sequence minOccurs="0">
         <element ref="t:FeatureType2"/>
      </sequence>
      <attributeGroup ref="gml:AssociationAttributeGroup"/>
      <attributeGroup ref="gml:OwnershipAttributeGroup"/>
   </complexType>
</schema>
