CREATE TABLE T3_CODELIST1 (

   CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
   DESCRIPTION VARCHAR2(255),
   NAME VARCHAR2(255),
   CUSTOMACTIVEINDICATORLF VARCHAR2(50),
   CUSTOMSOURCEGCLCOLUMN VARCHAR2(16)
);

CREATE TABLE T3_CODELIST2 (

   CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
   DESCRIPTION VARCHAR2(255),
   NAME VARCHAR2(255),
   CUSTOMACTIVEINDICATORLF VARCHAR2(50),
   CUSTOMSOURCEGCLCOLUMN VARCHAR2(16)
);

CREATE TABLE T3_FEATURETYPE1 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   PROPNUMCODE VARCHAR2(50) -- DEF: propNumCode definition; DESC: propNumCode description; EX: propNumCode example 1 propNumCode example 2; LB: propNumCode legal basis; DCS: propNumCode data capture statement 1 propNumCode data capture statement 2; PC: propNumCode primary code
);

CREATE TABLE T3_FEATURETYPE1_PROPALPCODE (

   T3_FEATURETYPE1_ID INTEGER NOT NULL,
   T3_CODELIST2_ID VARCHAR2(50) NOT NULL, -- DEF: ; DESC: ; EX: ; LB: ; DCS: ; PC:
   PRIMARY KEY (T3_FEATURETYPE1_ID, T3_CODELIST2_ID)
);

CREATE TABLE T3_YESNONACL (

   CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
   DESCRIPTION VARCHAR2(255),
   NAME VARCHAR2(255)
);


ALTER TABLE T3_CODELIST1 ADD CONSTRAINT FK_T3_CODEL_T3_YESNO_CUSTOMAC FOREIGN KEY (CUSTOMACTIVEINDICATORLF) REFERENCES T3_YESNONACL;
ALTER TABLE T3_CODELIST2 ADD CONSTRAINT FK_T3_CODEL_T3_YESNO_CUSTOMAC0 FOREIGN KEY (CUSTOMACTIVEINDICATORLF) REFERENCES T3_YESNONACL;
ALTER TABLE T3_FEATURETYPE1 ADD CONSTRAINT FK_T3_FEATU_T3_CODEL_PROPNUMC FOREIGN KEY (PROPNUMCODE) REFERENCES T3_CODELIST1;
ALTER TABLE T3_FEATURETYPE1_PROPALPCODE ADD CONSTRAINT FK_T3_FEATU_T3_CODEL_T3_CODEL FOREIGN KEY (T3_CODELIST2_ID) REFERENCES T3_CODELIST2;
ALTER TABLE T3_FEATURETYPE1_PROPALPCODE ADD CONSTRAINT FK_T3_FEATU_T3_FEATU_T3_FEATU FOREIGN KEY (T3_FEATURETYPE1_ID) REFERENCES T3_FEATURETYPE1;

INSERT INTO T3_YESNONACL (CODE, DESCRIPTION, NAME) VALUES ('No', 'No', '');
INSERT INTO T3_YESNONACL (CODE, DESCRIPTION, NAME) VALUES ('NotApplicable', 'NotApplicable', '');
INSERT INTO T3_YESNONACL (CODE, DESCRIPTION, NAME) VALUES ('Yes', 'Yes', '');
INSERT INTO T3_CODELIST1 (CODE, DESCRIPTION, NAME, CUSTOMACTIVEINDICATORLF, CUSTOMSOURCEGCLCOLUMN) VALUES ('1', 'code1', '', 'Yes', NULL);
INSERT INTO T3_CODELIST1 (CODE, DESCRIPTION, NAME, CUSTOMACTIVEINDICATORLF, CUSTOMSOURCEGCLCOLUMN) VALUES ('2', 'code2', '', 'Yes', NULL);
INSERT INTO T3_CODELIST1 (CODE, DESCRIPTION, NAME, CUSTOMACTIVEINDICATORLF, CUSTOMSOURCEGCLCOLUMN) VALUES ('quote''me', 'code3', '', 'Yes', NULL);
INSERT INTO T3_CODELIST2 (CODE, DESCRIPTION, NAME, CUSTOMACTIVEINDICATORLF, CUSTOMSOURCEGCLCOLUMN) VALUES ('code''B', 'code''B', 'codeB definition', 'Yes', NULL);
INSERT INTO T3_CODELIST2 (CODE, DESCRIPTION, NAME, CUSTOMACTIVEINDICATORLF, CUSTOMSOURCEGCLCOLUMN) VALUES ('codeA', 'codeA', 'codeA''s definition', 'Yes', NULL);
