:doctype: book
:encoding: utf-8
:lang: en
:toc: macro
:toc-title: Table of contents
:toclevels: 5

:toc-position: left

:appendix-caption: Annex

:numbered:
:sectanchors:
:sectnumlevels: 5

[[GML_32_Encoding_Rule]]
= GML 3.2 Encoding Rule

[[Source]]
== Source

http://portal.opengeospatial.org/files/?artifact_id=20509[GML 3.2, Annex
E]

[[Encoding_Rule_Identifier]]
== Encoding Rule Identifier

The GML 3.2 encoding rule has the identifier "iso19136_2007".

[[Conversion_Rules]]
== Conversion Rules

[[Overview]]
=== Overview

The following is a list of schema conversion rules that apply to the GML
3.2 encoding rule. These are in addition to
xref:./Conversion_Rule_Basics.adoc[the common conversion
rules].

[cols="1,3",options="header"]
|===
|Rule |Description

|rule-xsd-cls-codelist-asDictionary |If a the tagged value asDictionary
of a code list is not 'true', create a global type for the code list;
otherwise reference code list values using gml:CodeType

|rule-xsd-all-naming-gml |Use the naming strategy for schema components
as specified by GML 3.2

|rule-xsd-cls-noPropertyType |If a the tagged value noPropertyType of a
feature type, class, data type or union type is 'true', the property
type creation is suppressed

|rule-xsd-cls-byValuePropertyType |If a the tagged value
byValuePropertyType of a feature type or class is 'true', an additional
by-value property type is created

|rule-xsd-cls-standard-gml-property-types |Reuse property types or
create anonymous property types according to GML 3.2

|rule-xsd-pkg-gmlProfileSchema |Include gmlProfileSchema appinfo, if the
tagged value is set on the application schema package

|rule-xsd-prop-defaultCodeSpace |Include defaultCodeSpace appinfo, if
applicable

|rule-xsd-prop-inlineOrByReference |Take tagged value
inlineOrByReference on properties into account when setting the type of
a property element

|rule-xsd-prop-reverseProperty |Include reversePropertyName appinfo, if
applicable

|rule-xsd-prop-targetElement |Include targetElement appinfo, if a
property is byReference

|rule-xsd-cls-global-enumeration |Convert enumerations to global types
|===

[[rule-xsd-cls-codelist-asDictionary]]
=== rule-xsd-cls-codelist-asDictionary

If a the tagged value asDictionary of a code list is not 'true', create
a global type for the code list; otherwise reference code list values
using gml:CodeType

[[rule-xsd-all-naming-gml]]
=== rule-xsd-all-naming-gml

Use the naming strategy for schema components as specified by GML 3.2

[[rule-xsd-cls-noPropertyType]]
=== rule-xsd-cls-noPropertyType

If a the tagged value noPropertyType of a feature type, class, data type
or union type is 'true', the property type creation is suppressed

[[rule-xsd-cls-byValuePropertyType]]
=== rule-xsd-cls-byValuePropertyType

If a the tagged value byValuePropertyType of a feature type or class is
'true', an additional by-value property type is created

[[rule-xsd-cls-standard-gml-property-types]]
=== rule-xsd-cls-standard-gml-property-types

Reuse property types or create anonymous property types according to GML
3.2

[[rule-xsd-pkg-gmlProfileSchema]]
=== rule-xsd-pkg-gmlProfileSchema

Include gmlProfileSchema appinfo, if the tagged value is set on the
application schema package

[[rule-xsd-prop-defaultCodeSpace]]
=== rule-xsd-prop-defaultCodeSpace

Include defaultCodeSpace appinfo, if applicable

[[rule-xsd-prop-inlineOrByReference]]
=== rule-xsd-prop-inlineOrByReference

Take tagged value inlineOrByReference on properties into account when
setting the type of a property element

[[rule-xsd-prop-reverseProperty]]
=== rule-xsd-prop-reverseProperty

Include reversePropertyName appinfo, if applicable

[[rule-xsd-prop-targetElement]]
=== rule-xsd-prop-targetElement

Include targetElement appinfo, if a property is byReference

[[rule-xsd-cls-global-enumeration]]
=== rule-xsd-cls-global-enumeration

Convert enumerations to global types
