CREATE TABLE ASSOCIATIVETABLEOT1ANDFT1 (

   FEATURETYPE1_ID INTEGER NOT NULL,
   OBJECTTYPE1_ID INTEGER NOT NULL,
   PRIMARY KEY (FEATURETYPE1_ID, OBJECTTYPE1_ID)
);

CREATE TABLE CODELIST (

   CODE CLOB NOT NULL PRIMARY KEY,
   DOCUMENTATION CLOB
);

CREATE TABLE FEATURETYPE1 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ATTBOOLEANDEFAULTVALUE INTEGER DEFAULT 1 NOT NULL,
   ATTCHARACTERSTRINGDEFAULTVALUE VARCHAR2(1024) DEFAULT 'My default value' NOT NULL,
   ATTCHARACTERSTRINGLIMITEDLENGT VARCHAR2(200) NOT NULL,
   ATTCODELIST_FK CLOB NOT NULL,
   ATTINTEGERDEFAULTVALUE INTEGER DEFAULT 5 NOT NULL,
   ATTNUMERICENUMERATION NUMBER(5,2),
   ATTOPTIONALINTEGER INTEGER,
   ATTREALPRECISION NUMBER(8) NOT NULL,
   ATTREALPRECISIONSCALE NUMBER(5,2) NOT NULL,
   ATTTEXTENUMERATION VARCHAR2(1024) NOT NULL,
   ATTGUID RAW(16) NOT NULL,
   ATTMYREAL1 NUMBER(5) NOT NULL,
   ATTMYREAL2 NUMBER(5,2) NOT NULL,
   ATTPOINT SDO_GEOMETRY NOT NULL
);

CREATE TABLE FEATURETYPE2 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ROLEFT2TOOT1_FK INTEGER NOT NULL,
   ROLEFT2TOFT1_FK INTEGER NOT NULL
);

CREATE TABLE OBJECTTYPE1 (

   _ID INTEGER NOT NULL PRIMARY KEY,
   ROLEOT1TOFT2_FK INTEGER NOT NULL
);


ALTER TABLE ASSOCIATIVETABLEOT1ANDFT1 ADD CONSTRAINT FK_ASSOCIATIVETABLEOT1ANDFT1_F FOREIGN KEY (FEATURETYPE1_ID) REFERENCES FEATURETYPE1;
ALTER TABLE ASSOCIATIVETABLEOT1ANDFT1 ADD CONSTRAINT FK_ASSOCIATIVETABLEOT1ANDFT1_O FOREIGN KEY (OBJECTTYPE1_ID) REFERENCES OBJECTTYPE1;
ALTER TABLE FEATURETYPE1 ADD CONSTRAINT FEATURETYPE1_ATTNUMERICENU_CK CHECK (ATTNUMERICENUMERATION IS NULL OR ATTNUMERICENUMERATION IN (100.1, 100.2));
ALTER TABLE FEATURETYPE1 ADD CONSTRAINT FEATURETYPE1_ATTTEXTENUMER_CK CHECK (ATTTEXTENUMERATION IN ('X', 'Y'));
ALTER TABLE FEATURETYPE1 ADD CONSTRAINT FK_FEATURETYPE1_ATTCODELIST_FK FOREIGN KEY (ATTCODELIST_FK) REFERENCES CODELIST;
ALTER TABLE FEATURETYPE2 ADD CONSTRAINT FK_FEATURETYPE2_ROLEFT2TOFT1_F FOREIGN KEY (ROLEFT2TOFT1_FK) REFERENCES FEATURETYPE1;
ALTER TABLE FEATURETYPE2 ADD CONSTRAINT FK_FEATURETYPE2_ROLEFT2TOOT1_F FOREIGN KEY (ROLEFT2TOOT1_FK) REFERENCES OBJECTTYPE1;
ALTER TABLE OBJECTTYPE1 ADD CONSTRAINT FK_OBJECTTYPE1_ROLEOT1TOFT2_FK FOREIGN KEY (ROLEOT1TOFT2_FK) REFERENCES FEATURETYPE2;

INSERT INTO CODELIST (CODE, DOCUMENTATION) VALUES ('code1', '');
INSERT INTO CODELIST (CODE, DOCUMENTATION) VALUES ('code2', '');
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('FEATURETYPE1', 'ATTPOINT', MDSYS.SDO_DIM_ARRAY(FIXME), 4979);

CREATE INDEX IDX_FEATURETYPE1_ATTPOINT ON FEATURETYPE1 (ATTPOINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=point');
